const {imageURLGenerator, imageCaptionGenerator, nameGenerator} = require('./datagen')
const fs = require('fs')
const wStream = fs.createWriteStream('imgdata.txt');

const names = [
    "topspatial",
    "immigrantsigma",
    "learnedprocedure",
    "streamnotice",
    "weatherboardallagash",
    "rawbeefphoebe",
    "harmoniousgauze",
    "utterchicken",
    "obeisantbollihope",
    "padlockduality",
    "deformitylichfield",
    "crumbedonward",
    "pythonscroll",
    "brandydiplomas",
    "tamefossil",
    "unlovableunfunded",
    "sordqualifier",
    "keenlychocolate",
    "hannahrefinance",
    "filletssureness",
    "chloridesresource",
    "swoonedglorms",
    "termsavor",
    "murderdisastrous",
    "nustersstellar",
    "alumnirhyme",
    "insomniaby",
    "gafferbold",
    "debonairawkward",
    "empireprint",
    "mustardassist",
    "portionmuseum",
    "onslaughttrent",
    "samsonskelton",
    "detailsdelay",
    "debtorwolds",
    "puffsulfate",
    "unopenedmental",
    "zerosalacia",
    "impulsivebell",
    "cohesiveacting",
    "crossboo",
    "skierpassword",
    "larkjot",
    "cynonwork",
    "driverlunation",
    "refrigeratorundone",
    "fruitplubming",
    "strongounce",
    "puzzlinghelvetica",
    "threadresigned",
    "seatonwipeout",
    "appearancecish",
    "belatedcruttery",
    "lungcircus",
    "paragraphdiscussion",
    "jabberingnotation",
    "lichfieldtwillight",
    "southvisitor",
    "violetcolossal",
    "ununseptiumjegs",
    "scallionretrograde",
    "hotterslaptop",
    "blagcombustion",
    "stucksauna",
    "stabilityhumid",
    "entrylint",
    "missionneon",
    "baboonhide",
    "cancersounce",
    "nikkibagnet",
    "nosyfancied",
    "messagetyne",
    "anemicsettling",
    "faradachiness",
    "gooseoutlast",
    "civilflannel",
    "canolalanky",
    "signalcoaching",
    "remaketotally",
    "cabooseramrod",
    "sanktillsonburg",
    "hairgranitic",
    "flairheadbiddy",
    "anncityscape",
    "Mui",
    "Lucas",
    "Wesley",
    "Particia",
    "Adah",
    "Catherine",
    "Roxann",
    "Trinh",
    "Bryce",
    "Thomasena",
    "Hulda",
    "Kanesha",
    "Mariel",
    "Nathan",
    "Betsy",
    "Bertie",
    "Rheba",
    "Gilda",
    "Loree",
    "Sunny",
    "Brittny",
    "Branda",
    "Chae",
    "Laurence",
    "Leena",
    "Rachele",
    "Rene",
    "Shamika",
    "Marquerite",
    "Thi",
    "Verda",
    "Mindy",
    "Willodean",
    "Kendall",
    "Rhea",
    "Estelle",
    "Claudio",
    "Winona",
    "Saturnina",
    "Jerrica",
    "Susannah",
    "Sallie",
    "Margery",
    "Shawnta",
    "Bernarda",
    "Angle",
    "Julie",
    "Sharan",
    "Gordon",
    "Voncile",
    "Stevie",
    "Denver",
    "Vita",
    "Tom",
    "Florida",
    "Darci",
    "Eli",
    "Alida",
    "Tad",
    "Angila",
    "Preston",
    "Louetta",
    "Brigida",
    "Winston",
    "Mora",
    "Nikia",
    "Merna",
    "Irene",
    "Nery",
    "Juan",
    "Quinton",
    "Hipolito",
    "Cordell",
    "Rosamaria",
    "Imelda",
    "Elene",
    "Lamar",
    "Keila",
    "Melani",
    "Stephenie",
    "Rhiannon",
    "Janel",
    "Katelynn",
    "Aubrey",
    "Eve",
    "Felipe",
    "Kimberley",
    "Taina",
    "Carmela",
    "Ollie",
    "Margorie",
    "Sarai",
    "Shirl",
    "Reita",
    "Zoe",
    "Kamala",
    "Jenniffer",
    "Silvia",
    "Francoise",
    "Dara"
  ];

var i = 0
var prodid = 1


function write() {
    var ok = true;
    do {
        i++
        var image = `${i}|${imageURLGenerator()}|${names[Math.floor(Math.random() * names.length)]}|${imageCaptionGenerator()}\n`
        if(i === 15000000) {
            console.log('Woah, we\'re half way there')
        }
        if (i % 3 === 0) {
            prodid++
        }
        if (i === 30000000) {
            wStream.write(image, 'utf8', () => {
                wStream.end()
            });
        
        } else {
            ok = wStream.write(image, 'utf8');
        }
    } while (i < 30000000 && ok);
    if (i > 0) {
        wStream.once('drain', write);
    }
}
write()